export const cardTitles = {
  widgets: {
    title: {
      cryptoPortfolio: "Crypto portfolio balance",
      newConnection: "New Connections",
      projectSummary: "Project summary",
      newsLetter: "Newsletter subscription",
      flyingBird: "Flying bird",
      ourOffice: "Our office",
      eventInvite: "Digital Media Marketing Online Conference 2021",
      currentPlan: "Your current plan",
      weeklySales: "Weekly Sales",
      latestPosts: "Latest Posts",
      marketingCampaign: "Marketing campaign",
      currentProjects: "Current projects list",
      newRequests: "New Requests",
      recentActivities: "Recent Activities",
      taskListExpandable: "Tasks",
      dailyFeed: "Your daily feed",
      wordOfTheDay: "Word of the day",
      siteVisitors: "Website visitors",
      cryptoNews: "Crypto News",
    },
    subheader: {
      newConnection: "3 new connections",
      newsLetter: "Receive latest news and updates",
      flyingBird: "Music band",
      currencyCal: "9 Mar, 10:12 am UTC",
      eventInvite: "27th Aug, 09:30 pm EST",
      weeklySales: "Past two weeks",
      latestPosts: "Recently wrote articles",
      marketingCampaign: "Last Update 2021",
      currentProjects: "Recently updated projects",
      newRequests: "Recent new requests this week",
      taskListExpandable: "A complete todo list",
      siteVisitors: "Traffic received this week from around the globe",
    },
  },
};
