import Image from "../assets/images/400x400.png";
export const userPhotos = [
  {
    id: 1,
    photo_url: Image,
    caption: "Beauty with Beast",
    thumb: "",
    size: 2.5,
  },
  {
    id: 2,
    photo_url: Image,
    caption: "Nature Love",
    thumb: "",
    size: 2,
  },
  {
    id: 3,
    photo_url: Image,
    caption: "Forest",
    thumb: "",
    size: 3.5,
  },
  {
    id: 4,
    photo_url: Image,
    caption: "Nature at its best",
    thumb: "",
    size: 5,
  },
  {
    id: 5,
    photo_url: Image,
    caption: "Sea House",
    thumb: "",
    size: 3.5,
  },
  {
    id: 6,
    photo_url: Image,
    caption: "Minimal",
    thumb: "",
    size: 4,
  },
  {
    id: 7,
    photo_url: Image,
    caption: "Beauty with Beast",
    thumb: "",
    size: 2.5,
  },
  {
    id: 8,
    photo_url: Image,
    caption: "Nature Love",
    thumb: "",
    size: 2,
  },
  {
    id: 9,
    photo_url: Image,
    caption: "Forest",
    thumb: "",
    size: 3.5,
  },
  {
    id: 10,
    photo_url: Image,
    caption: "Nature at its best",
    thumb: "",
    size: 5,
  },
  {
    id: 11,
    photo_url: Image,
    caption: "Sea House",
    thumb: "",
    size: 3.5,
  },
  {
    id: 12,
    photo_url: Image,
    caption: "Minimal",
    thumb: "",
    size: 4,
  },
];
